name: Build Android APK

on:
  workflow_dispatch: {}  # run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Unzip project
        run: |
          unzip DinnerDecider_Android_Project.zip -d DinnerDecider

      # Optional: enable Places API key. Add a repository secret named PLACES_API_KEY to use this.
      - name: Write local.properties (optional)
        if: env.PLACES_API_KEY != ''
        run: |
          echo "PLACES_API_KEY=${{ env.PLACES_API_KEY }}" > DinnerDecider/local.properties
        env:
          PLACES_API_KEY: ${{ secrets.PLACES_API_KEY }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        working-directory: DinnerDecider
        run: gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DinnerDecider-debug-apk
          path: DinnerDecider/app/build/outputs/apk/debug/app-debug.apk

